keycloak:
  adminUser: admin
  adminPassword: adminpassword
  production: false
  httpEnabled: true
  proxyHeaders: "xforwarded"
  hostnameStrict: false
  hostnameStrictHttps: false
  extraArgs: 
    - "--http-host=0.0.0.0"
    - "--hostname-strict=false"

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

postgres:
  enabled: true
  auth:
    database: "keycloak"
    password: "keycloak-db-password"

persistence:
  enabled: true
  size: 2Gi