replicaCount: 1

keycloak:
  adminUser: "admin"
  adminPassword: "admin123"
  proxyHeaders: "xforwarded"
  production: false
  httpEnabled: true

cache:
  stack: "ispn"

postgres:
  enabled: true
  auth:
    database: "keycloak"
    username: "keycloak"
    password: "keycloakpassword"

persistence:
  enabled: true
  size: 1Gi
  accessModes:
    - ReadWriteOnce

ingress:
  enabled: false

service:
  type: ClusterIP