image:
  registry: docker.io
  repository: bitnamilegacy/keycloak
  tag: 26.1.0
  pullPolicy: IfNotPresent

auth:
  adminUser: admin
  adminPassword: "SuperSecureAdminPassword123"

service:
  type: ClusterIP
  ports:
    http: 80
    https: 443

production: false

postgresql:
  enabled: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 16.4.0
  auth:
    postgresPassword: "PostgresSuperPassword123"
    username: bn_keycloak
    password: "KeycloakDBPassword123"
    database: bitnami_keycloak
  primary:
    persistence:
      enabled: true
      size: 2Gi