architecture: standalone

auth:
  enabled: false

persistence:
  enabled: true
  size: 1Gi 
service:
  type: ClusterIP
  port: 6379

containerSecurityContext:
  runAsUser: 999
  runAsGroup: 999
  readOnlyRootFilesystem: true