apiVersion: cilium.io/v2
kind: CiliumExternalAuth
metadata:
  name: ext-authz-idp-config
  namespace: default
spec:
  httpService:
    serverUri:
      uri: http://oauth2-proxy.default.svc.cluster.local:4180
      cluster: k8s/default/oauth2-proxy:4180
      timeout: 5s
    authorizationRequest:
      allowedHeaders:
        patterns:
        - exact: cookie
        - exact: authorization
    authorizationResponse:
      allowedUpstreamHeaders:
        patterns:
        - exact: authorization
        - exact: x-auth-request-user
        - exact: x-auth-request-email