apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DEBUG: "True"
  DJANGO_SECRET_KEY: "your-super-secret-key-here"
  REDIS_URL: "redis://my-redis-master:6379/0"
  OIDC_RP_CLIENT_ID: "django-client"
  OIDC_RP_CLIENT_SECRET: "your-client-secret"
  OIDC_OP_AUTHORIZATION_ENDPOINT: "http://localhost:8080/realms/myrealm/protocol/openid-connect/auth"
  OIDC_OP_TOKEN_ENDPOINT: "http://my-keycloak.default.svc.cluster.local:8080/realms/myrealm/protocol/openid-connect/token"
  OIDC_OP_USER_ENDPOINT: "http://my-keycloak.default.svc.cluster.local:8080/realms/myrealm/protocol/openid-connect/userinfo"
  OIDC_OP_JWKS_ENDPOINT: "http://my-keycloak.default.svc.cluster.local:8080/realms/myrealm/protocol/openid-connect/certs"
  LOGIN_REDIRECT_URL: "/oidc/authenticate/"
  LOGOUT_REDIRECT_URL: "/"