apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: django-route
  namespace: default
spec:
  parentRefs:
  - name: my-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: ExternalAuth
      externalAuth:
        protocol: HTTP
        backendRef:
          group: ""
          kind: Service
          name: oauth2-proxy
          port: 4180
        http:
          allowedHeaders:
          - cookie
          - authorization
          allowedResponseHeaders:
          - authorization
          - x-auth-request-user
          - x-auth-request-email
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        remove:
        - x-auth-request-user
        - x-auth-request-email
    backendRefs:
    - name: django-service
      port: 80